# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.cache/wt [current_project]
set_property parent.project_path D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{d:/14.7/LabofCOAD/project2/Lab02 CPU实验环境搭建/Lab02 CPU实验环境搭建（学生版）/OExp02-IP2SOC/IP/Supplementary}} [current_project]
set_property ip_output_repo d:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/P.coe
add_files d:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/h.coe
read_mem {
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/VGA/vga_debugger.mem
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/VGA/font_8x16.mem
}
read_verilog -library xil_defaultlib {
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/Counter_x.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Ex_reg_Mem.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/ID_reg_Ex.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/IF_reg_ID.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/MIO_BUS.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Mem_reg_WB.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/Multi_8CH32.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/new/Pipeline_CPU.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_Ex.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_ID.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_IF.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_Mem.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OxExp05-Pipeline/OxExp05-Pipeline.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_WB.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/Supplementary/RAM_B.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/SAnti_jitter.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/SPIO.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/Framework/VGA.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/Framework/VgaController.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/Framework/VgaDebugger.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/Framework/VgaDisplay.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/clk_div.v
  D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/new/CSSTE.v
}
read_ip -quiet D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/ip/SSeg7_Dev_0/SSeg7_Dev_0.xci

read_ip -quiet d:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/ip/ROM_P/ROM_P.xci
set_property used_in_implementation false [get_files -all d:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/ip/ROM_P/ROM_P_ooc.xdc]

read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/Counter_x.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/SAnti_jitter.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/clk_div.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/SPIO.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/Multi_8CH32.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/IP/Supplementary/MIO_BUS.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/Supplementary/RAM_B.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_WB.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Mem_reg_WB.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_Mem.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Ex_reg_Mem.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_Ex.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/ID_reg_Ex.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_ID.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/IF_reg_ID.edf
read_edif D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/sources_1/imports/OExp05_Pipeline_CPU_example/Pipeline_IF.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/constrs_1/imports/OExp02-IP2SOC/Org-Sword.xdc
set_property used_in_implementation false [get_files D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_pipline/OExp02-IP2SOC.srcs/constrs_1/imports/OExp02-IP2SOC/Org-Sword.xdc]


synth_design -top CSSTE -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CSSTE.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CSSTE_utilization_synth.rpt -pb CSSTE_utilization_synth.pb"
