# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/Org-Sword.xdc

# IP: ip/ROM_D_0/ROM_D_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_D_0 || ORIG_REF_NAME==ROM_D_0} -quiet] -quiet
