webtalk_init -webtalk_dir D:/14.7/LabofCOAD/project5/OExp06-Cache/OExp06-Cache.sim/sim_1/behav/xsim/xsim.dir/cache_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 19 09:59:47 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212313180_0_0_408" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c2c81408-84f3-4a65-bd0c-0f018d8bc3af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "41df711072b146e9aaac7f3e4737ef9e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "251" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1540 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8808_KB" -context "xsim\\usage"
webtalk_transmit -clientid 640068590 -regid "212313180_0_0_408" -xml D:/14.7/LabofCOAD/project5/OExp06-Cache/OExp06-Cache.sim/sim_1/behav/xsim/xsim.dir/cache_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/14.7/LabofCOAD/project5/OExp06-Cache/OExp06-Cache.sim/sim_1/behav/xsim/xsim.dir/cache_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/14.7/LabofCOAD/project5/OExp06-Cache/OExp06-Cache.sim/sim_1/behav/xsim/xsim.dir/cache_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
