# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_inter/OExp02-IP2SOC.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/14.7/LabofCOAD/project5/OExp02-IP2SOC_inter/OExp02-IP2SOC.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/14.7/LabofCOAD/project5/OExp02-IP2SOC_inter/OExp02-IP2SOC.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/14.7/LabofCOAD/project5/OExp02-IP2SOC_inter/OExp02-IP2SOC.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
